### ISSUE TITLE
Please add licensing information

### ISSUE THREAD

**Issue by sandrobonazzola** [redhat-performance/satperf-fake-client#1]
This repository is lacking licensing information. As such, everything included in this repo is "All rights reserved".
Please note that in order to re-license this project you'll legally need ack from all existing contributors.

**Comment by jhutar** [comment]
Hello @sandrobonazzola . Please take a look. Should be OK now.

**Comment by jhutar** [comment]
Oh, forgot to ask @pablomh as you are the only other contributor. Are you OK with GPLv3?

**Comment by pablomh** [comment]
I've been always a BSD guy, but I'm fine with GPLv3 in this context :)

**Comment by sandrobonazzola** [comment]
Looks good, thanks!

**Comment by psuriset** [comment]
Thanks for adding @jhutar @sandrobonazzola .
@jhutar Can you please check our remaining repos as well.
